# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../base/deploy/

# list of resources to be Applied
patchesStrategicMerge:
- productpage-beta-deployment.yaml
- reviews-v3-deployment.yaml

