apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex
  namespace: gloo-system
spec:
  secretName: dex
  commonName: dex.jad.solo.io
  dnsNames: 
    - dex.jad.solo.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
