# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/baseline/edge
- bookinfo-cert.yaml
- gloo-argocd-virtualservice.yaml
- gloo-static-upstream-argocd-grpc.yaml
- argocd-cert.yaml
- gloo-dex-virtualservice.yaml
- dex-cert.yaml

# list of resources to be patched
patchesStrategicMerge:
- patch/gateway-proxy-service.yaml

