apiVersion: networking.mesh.gloo.solo.io/v1
kind: AccessPolicy
metadata:
  name: bookinfo-gateway-productpage-accesspolicy
  namespace: gloo-mesh
spec:
  destinationSelector:
  - kubeServiceMatcher:
      labels:
        service: productpage
      namespaces:
      - default
  sourceSelector:
  - kubeServiceAccountRefs:
      serviceAccounts:
      - clusterName: jad-cluster2
        name: istio-ingressgateway-service-account
        namespace: istio-system
      - clusterName: jad-cluster3
        name: istio-ingressgateway-service-account
        namespace: istio-system