apiVersion: networking.mesh.gloo.solo.io/v1
kind: AccessPolicy
metadata:
  name: bookinfo-productpage-details-reviews-accesspolicy
  namespace: gloo-mesh
spec:
  destinationSelector:
  - kubeServiceMatcher:
      labels:
        service: details
      namespaces:
      - default
  - kubeServiceMatcher:
      labels:
        service: reviews
      namespaces:
      - default
  sourceSelector:
  - kubeServiceAccountRefs:
      serviceAccounts:
      - clusterName: jad-cluster2
        name: bookinfo-productpage
        namespace: default
  - kubeServiceAccountRefs:
      serviceAccounts:
      - clusterName: jad-cluster3
        name: bookinfo-productpage
        namespace: default