apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: bookinfo.jad.solo.io
    service.beta.kubernetes.io/aws-load-balancer-name: jad-cluster1-istio-ingressgw-ns  
  name: istio-ingressgateway-ns
  namespace: istio-system
spec:
  type: LoadBalancer
