apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualGateway
metadata:
  name: enterprise-networking-virtualgateway
  namespace: gloo-mesh
spec:
  ingressGatewaySelectors:
  - portName: relay
    destinationSelectors:
    - kubeServiceMatcher:
        clusters:
          - jad-mgmt
        labels:
          ingressgateway.istio.io/direction: east-west
        namespaces:
        - istio-system
  connectionHandlers:
  - connectionMatch:
      serverNames:
      - relay.jad.solo.io
    tcp:
      tcpHosts:
      - name: gloo-mesh-enterprise-networking
        destination:
          kube:
            name: enterprise-networking
            namespace: gloo-mesh
            clusterName: mgmt