apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-edge-demo-http-vs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: gloo-edge/overlay/virtualservice/cloudflare-edge-demo/http/
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: false