apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-vs-gmg
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: bookinfo/overlay/config/domain/wildcard/gmg/north-south/1.1.a-route-cluster1/
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true