apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: blade/bookinfo/overlay/deploy/bookinfo2/
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo2
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true