apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../2.1.a-routing-tls-single-upstream
#- oidc-secret.yaml
#- extauthpolicy.yaml
- extauthserver.yaml

patchesStrategicMerge:
- patch/enable-oidc-auth.yaml