apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-cluster2-istio-ig-vs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: bookinfo/overlay/config/domain/wildcard/istio-ingressgateway/cluster1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true