# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../base/accesspolicy/

patchesStrategicMerge:
- patch/bookinfo-reviews-ratings-accesspolicy.yaml

namePrefix: bookinfo-reviews-ratings-