##################################################################################################
# Productpage services
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-beta
spec:
  replicas: 0
