apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-vs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: bookinfo/overlay/config/domain/wildcard/edge/1.2.a-route-multiple-upstream/
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true