apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop-vs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: hipstershop/overlay/virtualservice/istio/1-hipstershop-vs-frontend/
  destination:
    server: https://kubernetes.default.svc
    namespace: hipstershop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true