apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-backends
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: bookinfo/overlay/app/bookinfo-backends/no-reviews/
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo-backends
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true