apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-v1-mesh
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: bookinfo/overlay/bookinfo-v1/istio/
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo-v1
  syncPolicy:
    automated:
      prune: false
      selfHeal: false