apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualGateway
metadata:
  name: argocd-virtualgateway
  namespace: gloo-mesh
spec:
  ingressGatewaySelectors:
  - portName: https
    destinationSelectors:
    - kubeServiceMatcher:
        clusters:
        - jad-mgmt
        labels:
          ingressgateway.istio.io/direction: north-south
        namespaces:
        - istio-system
  connectionHandlers:
  - connectionOptions:
      sslConfig:
        secretName: argocd
        tlsMode: SIMPLE
    connectionMatch:
      serverNames:
      - argocd.jad.solo.io
    http:
      routeConfig:
      - virtualHostSelector:
          namespaces:
          - gloo-mesh
          labels:
            app: argocd

---

apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualGateway
metadata:
  name: argocd-virtualgateway-http-redirect
  namespace: gloo-mesh
spec:
  ingressGatewaySelectors:
  - portName: http2
    destinationSelectors:
    - kubeServiceMatcher:
        clusters:
          - jad-mgmt
        labels:
          ingressgateway.istio.io/direction: north-south
        namespaces:
        - istio-system
  connectionHandlers:
  - connectionOptions:
      httpsRedirect: true
    connectionMatch:
      serverNames:
      - argocd.jad.solo.io

