apiVersion: argoproj.io/v1alpha1
kind: Workflow 
metadata:
  generateName: lab2-ocp-
spec:
  entrypoint: kubectl 
  templates:
  - name: kubectl
    container:
      image: bitnami/kubectl
      command: [kubectl]
      args: ["version"]