apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator-helm-1-12-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-operator-1-12-2
  project: default
  source:
    repoURL: https://github.com/istio/istio.git
    path: manifests/charts/istio-operator
    targetRevision: 1.12.2
    helm:
      parameters:
      - name: hub
        value: docker.io/istio
      - name: tag
        value: 1.11.4
      - name: operatorNamespace
        value: istio-operator-1-12-2
      - name: istioNamespace
        value: istio-system
      - name: 1-12-2
      - name: global.hub
        value: docker.io/istio
      - name: global.tag
        value: 1.11.4
      - name: revision
        value: 1-12-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/labels
        - /spec/names/shortNames
