# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../base/deploy/

# list of resources to be patched
resources:
- productpage-beta-deployment.yaml
- productpage-beta-service.yaml

