# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- ../../../../../base/profiles/default/

patchesStrategicMerge:
- patch/istio-workshop-cluster3.yaml
- patch/version.yaml