apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: bookinfo
  namespace: gloo-system
spec:
  virtualHost:
    options:
      extauth:
        configRef:
          name: bookinfo-oidc-dex
          namespace: gloo-system
