apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: RouteTable
metadata:
  name: bookinfo-routetable
  namespace: gloo-mesh
spec:
  routes:
  - matchers:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    name: productpage
    options:
# ---------------- add retry config -----------------
      retries: 
        attempts: 3
# -------------------------------------------------------
    routeAction:
      destinations:
      - kubeService:
          clusterName: cluster2
          name: productpage
          namespace: default