##################################################################################################
# Productpage services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage-beta
  labels:
    app: productpage
    service: productpage
    version: beta
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage-beta

