apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-bookinfo-vs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: bookinfo/overlay/config/edge-virtualservice/cloudflare-edge-v2/1.1.a.route-single-upstream/
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true