apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: add-timeout-policy
spec:
  destinationSelector:
  - kubeServiceRefs:
      services:
        - clusterName: cluster2
          name: reviews
          namespace: default
  policy:
    requestTimeout: "0.25s"