apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-hipstershop-vs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: hipstershop/overlay/virtualservice/cloudflare-edge/2-hipstershop-vs-ratelimit/
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true