apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: bookinfo-routetable
  namespace: team1
  labels:
    application-owner: team1
spec:
  routes:
    - matchers:
        - prefix: /
      routeAction:
        single:
          upstream:
            name: bookinfo-productpage-9080
            namespace: gloo-system
#      options:
#        prefixRewrite: /productpage

