apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: north-south-gw
  namespace: istio-gateways
spec:
  listeners:
    - http: {}
      port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        secretName: tls-secret
      allowedRouteTables:
        - host: 'bookinfo1.jad.solo.io'