apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: RouteTable
metadata:
  name: bookinfo-routetable
  namespace: gloo-mesh
spec:
  routes:
  - matchers:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    name: productpage
# ---------------- rate limiting config -----------------
    options:
      rateLimit:
        raw:
          rateLimits:
          - setActions:
            - requestHeaders:
                descriptorKey: number
                headerName: x-number
            - requestHeaders:
                descriptorKey: type
                headerName: x-type
        ratelimitServerConfigSelector:
          namespaces:
          - gloo-mesh
# ---------------- add header config -----------------
      headerManipulation:
        appendResponseHeaders:
          "x-name": "foo"
          "x-type": "verified"
# -------------------------------------------------------
    routeAction:
      destinations:
      - kubeService:
          clusterName: cluster2
          name: productpage
          namespace: default