apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-v2-istio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: bookinfo/overlay/app/1.1.c-reviews-v3/istio/
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo-v2
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true