apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: control-plane
  #namespace: istio-system
spec:
  profile: empty
  revision: 1-11-5
  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway-1-11-5
      namespace: istio-ingress
      label:
          istio: ingressgateway
          version: 1-11-5
          app: istio-ingressgateway
      k8s:
        service:
          # Since we created our own LoadBalanced service, tell istio to create a ClusterIP service for this gateway
          type: ClusterIP
          # match the LoadBalanced Service
          ports:
            - name: status-port
              port: 15021
              targetPort: 15021
            - name: http2
              port: 80
              targetPort: 8080
            - name: https
              port: 443
              targetPort: 8443
            - name: tcp
              port: 31400
              targetPort: 31400
            - name: tls
              port: 15443
              targetPort: 15443
  values:
    #global:
      # needed for connecting VirtualMachines to the mesh
      #network: production-cluster-network
      # needed for annotating istio metrics with cluster
      #multiCluster:
        #clusterName: cluster1
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false