apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reviews-shift-failover
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: bookinfo/overlay/gloo-mesh-workshop/istio-ig/trafficshift-mgmt/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true