apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebs-csi-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: aws-ebs-csi-driver/aws-ebs-csi-driver
    repoURL: https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html
    targetRevision: 2.4.0
    helm:
      releaseName: aws-ebs-csi-driver
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true