apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: hipstershop-vs
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: cf-upstream-tls
      namespace: gloo-system