apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: blade/bookinfo/overlay/app/bookinfo1/
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo1
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true