apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: bookinfo-vs
  namespace: gloo-system
spec:
  virtualHost:
    routes:
    - matchers:
      - prefix: /
      options:
        prefixRewrite: /productpage