apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kapoozi-bookinfo-vs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: bookinfo/overlay/config/domain/kapoozi.com/edge/2.4.a-vhost-ratelimit/
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true