apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: gloo-system
spec:
  secretName: argocd
  commonName: argocd.jad.solo.io
  dnsNames: 
    - argocd.jad.solo.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
