apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../app/petstore/swaggerapi/
- ../../../app/petstore-portal
- ../../../config/petstore-portal/

patchesStrategicMerge:
- patch/portal-domain-patch.yaml
- patch/environment-domain-patch.yaml
- patch/tls-patch.yaml