# disable fed and require user to create a secret named "license" with base64 encoded gloo ee license key in the gloo-system namespace
--- 
create_license_secret: false
gloo: 
  license_secret_name: license
gloo-fed: 
  create_license_secret: false
  enabled: false
  glooFedApiserver: 
    enable: false
