# disable fed and require user to create a secret named "license" with base64 encoded gloo ee license key in the gloo-system namespace
gloo-fed:
  enabled: false
  create_license_secret: false
  glooFedApiserver:
    enable: false

gloo-ee:
  create_license_secret: false
  global:
    extensions:
      glooRedis:
        enableAcl: false
  gloo-fed:
    enabled: false
    create_license_secret: false
    glooFedApiserver:
      enable: false
  gloo:
    license_secret_name: "license"
    


    
