apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: add-abort-500-policy
spec:
  routeSelector:
  - virtualHostRefs:
    - name: demo-virtualhost
      namespace: gloo-mesh
  policy:
    faultInjection:
        abort:
          httpStatus: 500
        percentage: 100