##################################################################################################
# Productpage services
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-beta
  labels:
    app: productpage-beta
    version: beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage-beta
      version: beta
  template:
    metadata:
      labels:
        app: productpage-beta
        version: beta
    spec:
      serviceAccountName: bookinfo-productpage
      containers:
      - name: productpage
        image: docker.io/jjsadek/productpage-beta:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          runAsUser: 1000
      volumes:
      - name: tmp
        emptyDir: {}