apiVersion: portal.gloo.solo.io/v1beta1
kind: Environment
metadata:
  name: dev
  namespace: default
spec:
  apiProducts:
  - basePath: '{%version%}'
    labels:
    - key: app
      operator: In
      values:
      - petstore
    namespaces:
    - '*'
    usagePlans:
    - basic
    versions:
      names:
      - v1
      - v2
  basePath: /ecommerce
  displayInfo:
    description: This environment is meant for developers to deploy and test their
      APIs.
    displayName: Development
  domains:
  - api.mycompany.corp
  gatewayConfig:
    disableRoutes: false
  parameters:
    usagePlans:
      basic:
        authPolicy:
          apiKey: {}
        displayName: api-keys based plan
        rateLimit:
          requestsPerUnit: 5
          unit: MINUTE