apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
#- ../1-simple-cluster1/
- ../2c-multi/

resources:
- rl-config.yaml

patchesStrategicMerge:
- patches/bookinfo-routetable-patch.yaml