apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: http-vs
  namespace: gloo-system
spec:
  virtualHost:
    routes:
    - matchers:
      - prefix: /argo
      options:
        prefixRewrite: /argo
      routeAction:
        single:
          upstream:
            name: argocd-argocd-server-443
            namespace: gloo-system
    - matchers:
      - prefix: /keycloak/
      options:
        prefixRewrite: /auth/
      routeAction:
        single:
          upstream:
            name: default-keycloak-8080
            namespace: gloo-system
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-keycloak-8080
            namespace: gloo-system