apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-mesh-enterprise-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-mesh
  project: default
  source:
    chart: gloo-mesh-enterprise
    helm:
      parameters:
        - name: rbac-webhook.enabled
          value: 'false'
        - name: enterprise-networking.enterpriseNetworking.floatingUserId
          value: 'true'
        - name: rbac-webhook.rbacWebhook.floatingUserId
          value: 'true'
        - name: gloo-mesh-ui.dashboard.floatingUserId
          value: 'true'
        - name: gloo-mesh-ui.redis-dashboard.redisDashboard.floatingUserId
          value: 'true'
        - name: enterprise-networking.prometheus.server.securityContext
          value: 'false'
        - name: licenseKey
          value: '<INSERT_LICENSE_KEY_HERE>'
        - name: rbac-webhook.adminSubjects[0].kind
          value: 'User'
        - name: rbac-webhook.adminSubjects[0].name
          value: 'kube:admin'
    repoURL: https://storage.googleapis.com/gloo-mesh-enterprise/gloo-mesh-enterprise
    targetRevision: 1.2.16
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true