apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookinfo
  namespace: istio-system
spec:
  secretName: bookinfo
  commonName: bookinfo.jad.solo.io
  dnsNames: 
    - bookinfo.jad.solo.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
