apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  namespace: gloo-mesh
  name: add-abort-500-policy
spec:
  destinationSelector:
  - kubeServiceRefs:
      services:
        - clusterName: cluster1
          name: details
          namespace: default
        - clusterName: cluster1
          name: reviews
          namespace: default
        - clusterName: cluster1
          name: ratings
          namespace: default
        - clusterName: cluster2
          name: details
          namespace: default
        - clusterName: cluster2
          name: reviews
          namespace: default
        - clusterName: cluster2
          name: ratings
          namespace: default
  policy:
    faultInjection:
        abort:
          httpStatus: 500
        percentage: 100