apiVersion: portal.gloo.solo.io/v1beta1
kind: User
metadata:
  labels:
    app.kubernetes.io/instance: petstore-product
    groups.portal.gloo.solo.io/gloo-portal.developers: "true"
  name: developer1
  namespace: gloo-portal
spec:
  accessLevel:
    portals:
    - name: petstore-portal
      namespace: default
  basicAuth:
    passwordSecretKey: password
    passwordSecretName: developer1-password
    passwordSecretNamespace: gloo-portal
  username: developer1