apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-loadgen-istio-ingressgateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: bombardier-loadgen/overlay/bookinfo-loadgen-istio-ingressgateway/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).